[PHP]
extension_dir = "ext"
extension=zip
extension = openssl
extension = curl
extension = mbstring
extension = fileinfo
extension = pdo_mysql
date.timezone = UTC
allow_url_fopen = On

[curl]
curl.cainfo = "C:\Users\usuario\Downloads\WEBNIDA\tools\cacert.pem"

[openssl]
openssl.cafile = "C:\Users\usuario\Downloads\WEBNIDA\tools\cacert.pem"
